import logging
import datetime

import markdown as md
import weasyprint

logger = logging.getLogger(__name__)


class ThesisPDFGeneratorError(Exception):
    """Raised when PDF generation fails."""
    pass


class ThesisPDFGenerator:
    FONT_FAMILY: str = 'Times New Roman, serif'
    FONT_SIZE: str = '12pt'
    LINE_HEIGHT: str = '1.5'

    @classmethod
    def render(cls, thesis_text: str, title: str) -> bytes:
        """
        Convert thesis_text (markdown) to a styled HTML document and render
        to PDF bytes using WeasyPrint.
        Returns raw PDF bytes.
        Raises ThesisPDFGeneratorError on render failure.
        """
        try:
            html_string = cls._build_html(thesis_text, title)
            pdf_bytes = weasyprint.HTML(string=html_string).write_pdf()
            return pdf_bytes
        except Exception as e:
            logger.error('ThesisPDFGenerator failed: %s', e)
            raise ThesisPDFGeneratorError(f'PDF generation failed: {e}') from e

    @classmethod
    def _build_html(cls, thesis_text: str, title: str) -> str:
        """Convert markdown to HTML and wrap in full document template with CSS."""
        if '[TOC]' not in thesis_text:
            thesis_text = f"## Table of Contents\n\n[TOC]\n\n{thesis_text}"
            
        body_html = md.markdown(
            thesis_text,
            extensions=['extra', 'toc', 'nl2br'],
        )
        css = cls._get_css()
        current_date = datetime.date.today().strftime("%B %d, %Y")
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>{css}</style>
</head>
<body>
    <!-- Title Page -->
    <div class="title-page">
        <div class="title-page-content">
            <h1 class="thesis-title">{title}</h1>
            <p class="thesis-course">[Course Code / Name]</p>
            <p class="thesis-student">Student Name: [Your Name]</p>
            <p class="thesis-student">Student ID: [Your ID]</p>
            <p class="thesis-date">{current_date}</p>
            <p class="thesis-meta">Generated by LamGen</p>
        </div>
    </div>

    <!-- Main Content -->
    <div class="thesis-body">
        {body_html}
    </div>
</body>
</html>"""

    @classmethod
    def _get_css(cls) -> str:
        """Return the WeasyPrint CSS string for academic formatting."""
        return f"""
@page {{
    size: A4;
    margin: 2.5cm;
    @bottom-center {{
        content: "Page " counter(page);
        font-family: {cls.FONT_FAMILY};
        font-size: 10pt;
    }}
}}

@page :first {{
    @bottom-center {{ content: none; }}
}}

body {{
    font-family: {cls.FONT_FAMILY};
    font-size: {cls.FONT_SIZE};
    line-height: {cls.LINE_HEIGHT};
    color: #000000;
    text-align: justify;
}}

.title-page {{
    page-break-after: always;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 25cm;
    text-align: center;
}}

.title-page-content {{
    padding: 2cm;
}}

.thesis-title {{
    font-size: 18pt;
    font-weight: bold;
    text-transform: uppercase;
    margin-bottom: 2cm;
    line-height: 1.5;
}}

.thesis-course {{
    font-size: 14pt;
    font-weight: bold;
    margin-bottom: 2cm;
}}

.thesis-student {{
    font-size: 12pt;
    margin-bottom: 0.5cm;
}}

.thesis-date {{
    font-size: 12pt;
    margin-bottom: 3cm;
}}

.thesis-meta {{
    font-size: 10pt;
    margin-top: 2cm;
    color: #555;
}}

.thesis-body {{
    counter-reset: page 1;
}}

h1 {{
    font-size: 16pt;
    font-weight: bold;
    text-align: center;
    text-transform: uppercase;
    margin-top: 2em;
    margin-bottom: 1em;
    page-break-before: always;
}}

h1:first-child {{
    page-break-before: avoid;
}}

h2 {{
    font-size: 14pt;
    font-weight: bold;
    margin-top: 1.5em;
    margin-bottom: 0.75em;
    border-bottom: 1px solid #ccc;
    padding-bottom: 0.25em;
}}

h3 {{
    font-size: 12pt;
    font-weight: bold;
    margin-top: 1em;
    margin-bottom: 0.5em;
}}

p {{
    margin-bottom: 12px;
}}

ul, ol {{
    margin-left: 1.5cm;
    margin-bottom: 0.5em;
}}

li {{
    margin-bottom: 0.25em;
}}

blockquote {{
    margin: 1em 2cm;
    font-style: italic;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
    font-size: 11pt;
}}

th, td {{
    border: 1px solid #000;
    padding: 0.3cm 0.5cm;
    text-align: left;
}}

th {{
    font-weight: bold;
    background-color: #f0f0f0;
}}

.toc {{
    margin: 2em 0;
    page-break-after: always;
}}

.toc ul {{
    list-style-type: none;
    padding-left: 0;
}}

.toc li {{
    margin-bottom: 0.5em;
}}

.toc a {{
    text-decoration: none;
    color: #000;
}}
"""
