[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --cov=. --cov-report=term-missing --cov-fail-under=80 --cov-omit=*/migrations/*,*/tests/*,manage.py,*/wsgi.py,*/celery.py
