# Generated by Django 4.2.16 on 2026-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_add_seo_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Custom canonical URL', max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic content blocks for the page'),
        ),
        migrations.AddField(
            model_name='tool',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='List of tool usage examples'),
        ),
        migrations.AddField(
            model_name='tool',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of target keywords'),
        ),
        migrations.AddField(
            model_name='tool',
            name='last_content_update',
            field=models.DateTimeField(auto_now=True, help_text='Track when SEO content was last updated'),
        ),
        migrations.AddField(
            model_name='tool',
            name='og_image',
            field=models.CharField(blank=True, help_text='Custom OG image path', max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='schema_type',
            field=models.CharField(choices=[('SoftwareApplication', 'SoftwareApplication'), ('WebPage', 'WebPage'), ('Service', 'Service')], default='SoftwareApplication', max_length=30),
        ),
        migrations.AddField(
            model_name='tool',
            name='searchable_tags',
            field=models.JSONField(blank=True, default=list, help_text='Enhanced searchable tags'),
        ),
        migrations.AddField(
            model_name='tool',
            name='word_count_target',
            field=models.IntegerField(default=1200, help_text='Target word count for SEO content'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='avg_session_duration',
            field=models.FloatField(default=0.0, help_text='Average session duration in seconds'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='best_use_cases',
            field=models.JSONField(blank=True, default=list, help_text='Category-level use cases'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='bounce_rate',
            field=models.FloatField(default=0.0, help_text='Bounce rate percentage'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='category_faq',
            field=models.JSONField(blank=True, default=list, help_text='Category-level FAQ items'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='category_intro',
            field=models.TextField(blank=True, help_text='Category introduction for SEO landing page'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='featured_tools',
            field=models.JSONField(blank=True, default=list, help_text='List of featured tool slugs'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='keyword_variations',
            field=models.JSONField(blank=True, default=list, help_text='Keyword variations for the category'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='last_analytics_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='related_guides',
            field=models.JSONField(blank=True, default=list, help_text='Related guide URLs'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='related_subcategories',
            field=models.JSONField(blank=True, default=list, help_text='Related subcategory slugs'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Category page meta description', max_length=160),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Category page SEO title', max_length=70),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='total_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
