# Generated by Django 4.2.16 on 2026-05-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_expand_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='cache_strategy',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_ai_powered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='search_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tools.toolcategory'),
        ),
    ]
