# Generated by Django 4.2.16 on 2026-05-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_tool_cache_strategy_tool_is_ai_powered_and_more'),
        ('tools', '0009_tool_registry_version'),
    ]

    operations = [
    ]
