# Generated by Django 4.2.16 on 2026-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('health_score', models.FloatField(default=1.0)),
                ('latency', models.PositiveIntegerField(default=0)),
                ('failure_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='aiproviderusage',
            name='provider_name',
        ),
        migrations.AddField(
            model_name='aiproviderusage',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_providers.aiprovider'),
        ),
    ]
