# Generated by Django 4.2.16 on 2026-04-30 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentbrief',
            name='esl_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedsection',
            name='ai_suspicion_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedsection',
            name='refinement_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentbrief',
            name='assignment_type',
            field=models.CharField(choices=[('essay', 'Essay'), ('report', 'Report'), ('case_study', 'Case Study'), ('literature_review', 'Literature Review'), ('thesis_chapter', 'Thesis Chapter'), ('other', 'Other'), ('reflection', 'Reflection'), ('critique', 'Critique'), ('research_paper', 'Research Paper'), ('policy_analysis', 'Policy Analysis'), ('technical_documentation', 'Technical Documentation'), ('business_report', 'Business Report'), ('dissertation', 'Dissertation'), ('presentation', 'Presentation'), ('mixed_format', 'Mixed Format')], max_length=30),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ANALYSING', 'Analysing'), ('AWAITING_OUTLINE_REVIEW', 'Awaiting Outline Review'), ('PROCESSING', 'Processing'), ('REFINING', 'Refining'), ('REFINEMENT_COMPLETE', 'Refinement Complete'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='RefinementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_readiness_score', models.FloatField()),
                ('ai_suspicion_score', models.FloatField()),
                ('human_realism_score', models.FloatField()),
                ('rubric_coverage_score', models.FloatField()),
                ('citation_completeness_score', models.FloatField()),
                ('word_count_compliant', models.BooleanField()),
                ('auto_refinement_triggered', models.BooleanField(default=False)),
                ('refinement_passes_log', models.JSONField(default=list)),
                ('export_generated', models.BooleanField(default=False)),
                ('total_refinement_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('cache_hit_count', models.IntegerField(default=0)),
                ('llm_calls_count', models.IntegerField(default=0)),
                ('static_analysis_calls_count', models.IntegerField(default=0)),
                ('skipped_stages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refinement_result', to='generation.generationjob')),
            ],
        ),
    ]
