# Generated by Django 4.2.16 on 2026-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_generationjob_user_hints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentbrief',
            name='esl_context',
        ),
        migrations.RemoveField(
            model_name='generatedsection',
            name='ai_suspicion_score',
        ),
        migrations.RemoveField(
            model_name='generatedsection',
            name='refinement_version',
        ),
        migrations.AlterField(
            model_name='assignmentbrief',
            name='assignment_type',
            field=models.CharField(choices=[('essay', 'Essay'), ('report', 'Report'), ('case_study', 'Case Study'), ('literature_review', 'Literature Review'), ('thesis_chapter', 'Thesis Chapter'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ANALYSING', 'Analysing'), ('AWAITING_OUTLINE_REVIEW', 'Awaiting Outline Review'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.DeleteModel(
            name='RefinementResult',
        ),
    ]
