"""String templates for deterministic SEO content generation."""

CONTENT_TEMPLATES: dict[str, list[str]] = {
    'captions': [
        "{adj} {noun}s like this don't happen every day. ✨ #{topic}",
        "Every {noun} tells a story. This one is {adj}. 📸 #{topic}",
        "Chasing {adj} {noun}s and loving every second. 🌟",
        "Living for moments that feel this {adj}. #{topic}",
        "Not all who {verb} are lost — some are just finding their {noun}. 🌍",
        "The {adj} {noun} you've been waiting for. #{topic}",
        "When the {noun} hits different. 💫 #{topic}",
        "This is what {emotion} looks like. #{topic}",
        "Collect {noun}s, not things. ✈️ #{topic}",
        "{verb} more, worry less. #{topic}",
        "Fuelled by {emotion} and {adj} {noun}s. ☕",
        "Some {noun}s are worth every second. #{topic}",
        "The {adj} kind of {noun}. Always. #{topic}",
        "Here for the {adj} {noun}s and the {emotion}. 🙌",
        "Life is too short for anything less than {adj}. #{topic}",
        "Making {noun}s out of {adj} days. 🌈",
        "This {noun} brought me pure {emotion}. #{topic}",
        "Not just a {noun} — a whole {emotion}. ✨",
        "{verb} until it feels {adj}. #{topic}",
        "The {noun} that started it all. #{topic}",
        "Grateful for every {adj} {noun}. 🙏 #{topic}",
        "When {emotion} meets a {adj} {noun}. 💛",
        "Just a {noun} chasing {adj} skies. ☁️ #{topic}",
        "This is my kind of {adj}. #{topic}",
        "Proof that {adj} {noun}s exist. 📍 #{topic}",
    ],
    'quotes': [
        "The {adj} path to {noun} is through consistent {verb}.",
        "Your {noun} is defined by your {emotion}, not your circumstances.",
        "{verb} with {emotion}. Rest with {adj} purpose.",
        "The most {adj} thing you can do is {verb} when it's hard.",
        "{emotion} is not a destination — it's a way of {verb}ing.",
        "Small {adj} actions lead to {noun} results.",
        "You don't need to be {adj} to start. You need to start to be {adj}.",
        "The secret to {noun} is to {verb} before you feel ready.",
        "Every {adj} {noun} begins with a single {adj} decision.",
        "Your {noun} is your responsibility. {verb} it with {emotion}.",
        "Don't wait for {adj} conditions. {verb} in the chaos.",
        "The {adj} mind sees {noun} where others see obstacles.",
        "{verb} hard in silence. Let your {noun} make the noise.",
        "One {adj} step forward is still progress toward your {noun}.",
        "The {noun} you want is on the other side of {emotion}.",
        "Be {adj} enough to {verb} and wise enough to persist.",
        "Your {noun} doesn't care about your excuses. {verb}.",
        "The {adj} truth: {noun} requires {emotion} every single day.",
        "Stop waiting. Start {verb}ing. Build your {noun}.",
        "A {adj} mindset turns every {noun} into an opportunity.",
    ],
    'interview-questions': [
        "What is the difference between {noun} and {adj} {noun} in {topic}?",
        "Explain how you would {verb} a {noun} in {topic}.",
        "How does {noun} work in the context of {topic}?",
        "What are the {adj} challenges when working with {noun} in {topic}?",
        "Describe a time you had to {verb} a {adj} {noun} problem in {topic}.",
        "What is the time complexity of {verb}ing a {noun} in {topic}?",
        "How would you {verb} a {noun} for {adj} performance in {topic}?",
        "What are the best practices for {noun} in {topic}?",
        "Explain the {adj} approach to {verb}ing {noun} in {topic}.",
        "What tools do you use to {verb} {noun} in {topic}?",
        "How do you handle {adj} {noun} scenarios in {topic}?",
        "What is your approach to {verb}ing {noun} at scale in {topic}?",
        "Describe the {adj} pattern for {noun} in {topic}.",
        "How would you test a {noun} implementation in {topic}?",
        "What are the trade-offs between different {noun} approaches in {topic}?",
        "How do you ensure {adj} {noun} in a {topic} system?",
        "Walk me through your process for {verb}ing {noun} in {topic}.",
        "What is the most {adj} mistake developers make with {noun} in {topic}?",
        "How does {noun} affect {adj} performance in {topic}?",
        "What would you change about how {noun} is handled in {topic}?",
    ],
    'bios': [
        "{adj} {noun} with a passion for {verb}ing {adj} things.",
        "I {verb} {adj} {noun}s that make a real difference.",
        "{adj} {noun} | {verb}ing ideas into reality | {emotion}",
        "Helping people {verb} through {adj} {noun}s. #{topic}",
        "{adj} {noun} by day, {adj} creator by night.",
        "On a mission to {verb} {adj} {noun}s for everyone.",
        "{emotion}-driven {noun} who loves to {verb} and inspire.",
        "Building {adj} {noun}s with {emotion} and purpose.",
        "{adj} {noun} | {verb}ing the future one step at a time.",
        "Turning {adj} ideas into {noun}s that matter.",
        "{verb}ing {adj} {noun}s since day one. #{topic}",
        "Fuelled by {emotion} and {adj} {noun}s. Let's {verb}.",
        "{adj} {noun} obsessed with {verb}ing things better.",
        "I {verb} {adj} {noun}s. That's it. That's the bio.",
        "{emotion} is my superpower. {adj} {noun} is my craft.",
    ],
    'usernames': [
        "{adj}_{noun}_{number}",
        "the_{adj}_{noun}",
        "{noun}_{adj}x",
        "_{adj}{noun}_",
        "{adj}.{noun}.{number}",
        "real_{adj}_{noun}",
        "{noun}_{number}_{adj}",
        "x_{adj}_{noun}_x",
        "{adj}{noun}official",
        "not_{adj}_{noun}",
        "just_{adj}_{noun}",
        "{adj}_{noun}_irl",
        "im_{adj}_{noun}",
        "{noun}_{adj}_vibes",
        "the_real_{adj}_{noun}",
    ],
    'hashtags': [
        "#{topic}{adj}",
        "#{adj}{noun}",
        "#{topic}community",
        "#{topic}daily",
        "#{topic}life",
        "#{topic}tips",
        "#{topic}goals",
        "#{topic}motivation",
        "#{topic}inspiration",
        "#{topic}growth",
        "#{topic}success",
        "#{topic}mindset",
        "#{topic}hustle",
        "#{topic}creator",
        "#{topic}vibes",
        "#{topic}content",
        "#{topic}strategy",
        "#{topic}expert",
        "#{topic}pro",
        "#{topic}master",
    ],
    'thesis-topics': [
        "A {adj} analysis of {noun} in {topic}",
        "The {adj} impact of {noun} on {topic}: An {adj} study",
        "{verb}ing {noun} in {topic}: A {adj} framework",
        "Toward a {adj} model of {noun} in {topic}",
        "The role of {noun} in {adj} {topic} systems",
        "A {adj} review of {noun} approaches in {topic}",
        "{adj} {noun} strategies in {topic}: Evidence and implications",
        "Understanding {noun} in {topic}: A {adj} perspective",
        "{verb}ing {adj} {noun} in {topic}: Challenges and opportunities",
        "The {adj} relationship between {noun} and {topic}",
        "A {adj} examination of {noun} within {topic}",
        "{noun} and {topic}: A {adj} comparative study",
        "Rethinking {noun} in {topic}: A {adj} approach",
        "The {adj} dimensions of {noun} in {topic}",
        "{adj} {noun} in {topic}: Theory, practice, and future directions",
    ],
    'project-ideas': [
        "Build a {adj} {noun} for {topic} using modern web technologies",
        "Create an {adj} {noun} that helps users {verb} in {topic}",
        "Develop a {adj} {topic} {noun} with real-time features",
        "Design a {adj} {noun} to {verb} {topic} workflows",
        "Build an open-source {noun} for {topic} developers",
        "Create a {adj} {topic} dashboard with analytics",
        "Develop a {adj} CLI {noun} for {topic} automation",
        "Build a {adj} {noun} API for {topic} integration",
        "Create a {adj} {topic} {noun} with AI-powered features",
        "Design a {adj} mobile {noun} for {topic} management",
        "Build a {adj} {noun} that simplifies {topic} for beginners",
        "Develop a {adj} {topic} {noun} with offline support",
        "Create a {adj} {noun} for {topic} collaboration",
        "Build a {adj} {topic} {noun} with real-time notifications",
        "Design a {adj} {noun} to automate {topic} tasks",
    ],
    'default': [
        "{number} {adj} ways to use {topic} effectively",
        "The {adj} guide to {topic} for beginners",
        "How to {verb} {topic} like a professional",
        "{adj} {topic} tips that actually work",
        "Everything you need to know about {topic}",
        "The most {adj} {topic} resources available",
        "Why {topic} is more {adj} than you think",
        "{verb}ing {topic}: A {adj} approach",
        "The {adj} truth about {topic}",
        "{number} reasons why {topic} matters",
    ],
}
