# Generated by Django 4.2.16 on 2026-04-29 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('subject_area', models.CharField(max_length=255)),
                ('assignment_type', models.CharField(choices=[('essay', 'Essay'), ('report', 'Report'), ('case_study', 'Case Study'), ('literature_review', 'Literature Review'), ('thesis_chapter', 'Thesis Chapter'), ('other', 'Other')], max_length=30)),
                ('academic_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctoral', 'Doctoral')], max_length=20)),
                ('academic_level_inferred', models.BooleanField(default=False)),
                ('required_sections', models.JSONField(default=list)),
                ('citation_style', models.CharField(max_length=50)),
                ('formatting_instructions', models.TextField(blank=True)),
                ('required_frameworks', models.JSONField(default=list)),
                ('writing_tone', models.CharField(choices=[('critical_analytical', 'Critical Analytical'), ('descriptive_explanatory', 'Descriptive Explanatory'), ('reflective', 'Reflective'), ('professional_report', 'Professional Report')], max_length=30)),
                ('organisational_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('input_file', models.FileField(blank=True, upload_to='uploads/')),
                ('prompt_text', models.TextField(blank=True)),
                ('target_word_count', models.PositiveIntegerField(default=3000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYSING', 'Analysing'), ('AWAITING_OUTLINE_REVIEW', 'Awaiting Outline Review'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('output_docx', models.FileField(blank=True, upload_to='outputs/')),
                ('output_pdf', models.FileField(blank=True, upload_to='outputs/')),
                ('generated_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_logs', to='generation.generationjob')),
            ],
        ),
        migrations.CreateModel(
            name='RubricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='generation.assignmentbrief')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=list)),
                ('research_context', models.JSONField(default=dict)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='generation.generationjob')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentbrief',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='generation.generationjob'),
        ),
        migrations.CreateModel(
            name='GeneratedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('humanized', models.BooleanField(default=False)),
                ('reviewer_score', models.JSONField(blank=True, null=True)),
                ('rewritten_by_reviewer', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='generation.generationjob')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'order')},
            },
        ),
    ]
