# Generated by Django 4.2.16 on 2026-05-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('title_template', models.CharField(default='{topic} Ideas', help_text='Use {topic} placeholder. E.g. "{topic} Instagram Captions — 100+ Ideas"', max_length=200)),
                ('meta_desc_template', models.CharField(default='Browse {count}+ {topic} ideas. Free, curated, and ready to use.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'SEO Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content_intro', models.TextField(blank=True)),
                ('items', models.JSONField(default=list, help_text='Array of content items')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('view_count', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='seo.seocategory')),
            ],
            options={
                'ordering': ['category', 'topic'],
            },
        ),
    ]
