# Generated by Django 4.2.16 on 2026-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_longtailvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtailvariant',
            name='faq_items',
            field=models.JSONField(default=list, help_text="List of {'q', 'a'} FAQ dicts"),
        ),
        migrations.AddField(
            model_name='longtailvariant',
            name='use_cases',
            field=models.JSONField(default=list, help_text='List of use case strings'),
        ),
        migrations.AlterField(
            model_name='longtailvariant',
            name='unique_intro',
            field=models.TextField(help_text='Unique 200-300 word intro for this variant'),
        ),
    ]
