# config/journeys.py
# Journey Registry — single source of truth for all narrative journeys.
# Each journey maps user intent → progressive steps → tools → outcome.

JOURNEYS = [
    {
        "slug": "get-a-job",
        "name": "Get a Job",
        "tagline": "Land your dream role — step by step",
        "icon": "bi-briefcase-fill",
        "color_from": "#7B6FFF",
        "color_to": "#3EECD8",
        "emoji": "💼",
        "problem": "You're job hunting but your resume is weak, your cover letter is generic, and you don't stand out on LinkedIn. Most applications disappear into the void.",
        "outcome": "A job-ready resume, a targeted cover letter, and an optimized LinkedIn profile — ready to apply with confidence.",
        "category_slug": "resume-career-tools",
        "steps": [
            {
                "step": 1,
                "title": "Check Your Current Resume",
                "desc": "See how your resume scores against ATS systems before applying anywhere.",
                "why": "90% of resumes are filtered by ATS before a human ever sees them. Know your score first.",
                "input_hint": "Paste your current resume text",
                "output": "ATS score, keyword gaps, and improvement list",
                "tool_slug": "ai-ats-resume-checker",
                "tool_name": "AI ATS Resume Checker",
            },
            {
                "step": 2,
                "title": "Build a Job-Winning Resume",
                "desc": "Generate a professional, tailored resume using your background and target role.",
                "why": "A well-structured resume gets 3× more callbacks than a generic one.",
                "input_hint": "Your job title, skills, experience, and education",
                "output": "Complete professional resume ready to send",
                "tool_slug": "ai-resume-builder",
                "tool_name": "AI Resume Builder",
            },
            {
                "step": 3,
                "title": "Write a Tailored Cover Letter",
                "desc": "Create a compelling cover letter that speaks directly to the job description.",
                "why": "Hiring managers spend 6 seconds on a resume. A great cover letter buys you more.",
                "input_hint": "Job description + your background",
                "output": "Personalized cover letter ready to send",
                "tool_slug": "ai-cover-letter-generator",
                "tool_name": "AI Cover Letter Generator",
            },
            {
                "step": 4,
                "title": "Craft a Standout LinkedIn Headline",
                "desc": "Generate a LinkedIn headline that attracts recruiters and hiring managers.",
                "why": "Your LinkedIn headline is the first thing recruiters see — make it count.",
                "input_hint": "Your role, skills, and value proposition",
                "output": "5 headline options ranked by impact",
                "tool_slug": "ai-linkedin-headline-generator",
                "tool_name": "AI LinkedIn Headline Generator",
            },
            {
                "step": 5,
                "title": "Post on LinkedIn to Get Noticed",
                "desc": "Write an engaging LinkedIn post that showcases your expertise and attracts opportunities.",
                "why": "Active LinkedIn users get 4× more profile views and connection requests.",
                "input_hint": "Your career milestone or insight to share",
                "output": "Engaging LinkedIn post ready to publish",
                "tool_slug": "ai-linkedin-post-generator",
                "tool_name": "AI LinkedIn Post Generator",
            },
        ],
    },
    {
        "slug": "start-a-business",
        "name": "Start a Business",
        "tagline": "Go from idea to launch — in one narrative",
        "icon": "bi-rocket-takeoff-fill",
        "color_from": "#F59E0B",
        "color_to": "#EF4444",
        "emoji": "🚀",
        "problem": "You have an idea but no name, no plan, and no clear path. Every tab you open leads to overwhelm.",
        "outcome": "A named, positioned business with a plan, a brand identity direction, and a launch-ready content strategy.",
        "category_slug": "finance-business-tools",
        "steps": [
            {
                "step": 1,
                "title": "Name Your Business",
                "desc": "Generate creative, memorable startup names that fit your market and vision.",
                "why": "The right name is your first impression, your SEO anchor, and your brand foundation.",
                "input_hint": "Your idea, target market, and desired brand feel",
                "output": "10+ startup name ideas with domain availability hints",
                "tool_slug": "startup-name-generator",
                "tool_name": "AI Startup Name Generator",
            },
            {
                "step": 2,
                "title": "Draft Your Business Plan",
                "desc": "Generate a structured business plan outline to validate and communicate your idea.",
                "why": "A plan forces you to think through every dimension — before you spend a dollar.",
                "input_hint": "Business concept, target audience, and value proposition",
                "output": "Complete business plan with sections ready to fill",
                "tool_slug": "business-plan-generator",
                "tool_name": "AI Business Plan Generator",
            },
            {
                "step": 3,
                "title": "Create a Logo Prompt",
                "desc": "Generate detailed AI prompts to create your brand logo using image generators.",
                "why": "Visual identity communicates trust before a single word is read.",
                "input_hint": "Brand name, industry, and aesthetic direction",
                "output": "Logo prompt ready for Midjourney, DALL-E, or Stable Diffusion",
                "tool_slug": "logo-prompt-generator",
                "tool_name": "Logo Prompt Generator",
            },
            {
                "step": 4,
                "title": "Estimate Your Startup Costs",
                "desc": "Get a realistic cost breakdown for your business before spending anything.",
                "why": "Most startups fail from cash flow problems, not bad ideas. Know your numbers.",
                "input_hint": "Business type and key cost categories",
                "output": "Itemized cost estimate with priority flags",
                "tool_slug": "startup-cost-estimator",
                "tool_name": "Startup Cost Estimator",
            },
            {
                "step": 5,
                "title": "Write Your First Blog Post",
                "desc": "Launch your content engine with an SEO-optimized blog post about your space.",
                "why": "Content marketing is the highest-ROI growth channel for new businesses.",
                "input_hint": "Topic related to your industry or product",
                "output": "Full SEO blog post ready to publish",
                "tool_slug": "blog-writer",
                "tool_name": "AI Blog Writer",
            },
        ],
    },
    {
        "slug": "write-and-publish",
        "name": "Write & Publish",
        "tagline": "From blank page to published content",
        "icon": "bi-pencil-square",
        "color_from": "#8B5CF6",
        "color_to": "#EC4899",
        "emoji": "✍️",
        "problem": "You have ideas but writing takes too long, your grammar is shaky, and you're not sure if your content will rank.",
        "outcome": "Polished, plagiarism-free, SEO-ready content published with confidence.",
        "category_slug": "writing-tools",
        "steps": [
            {
                "step": 1,
                "title": "Write Your First Draft",
                "desc": "Generate a complete essay or article draft using your topic and requirements.",
                "why": "Starting is the hardest part. A working draft beats a blank page every time.",
                "input_hint": "Your topic, audience, and key points to cover",
                "output": "Full draft essay or article",
                "tool_slug": "essay-writer",
                "tool_name": "AI Essay Writer",
            },
            {
                "step": 2,
                "title": "Fix Grammar & Clarity",
                "desc": "Check and correct grammar, spelling, and sentence structure throughout your draft.",
                "why": "Errors kill credibility instantly — readers stop trusting you the moment they spot one.",
                "input_hint": "Your draft text",
                "output": "Corrected, polished version of your text",
                "tool_slug": "grammar-checker",
                "tool_name": "AI Grammar Checker",
            },
            {
                "step": 3,
                "title": "Rewrite to Avoid Plagiarism",
                "desc": "Paraphrase and rephrase your content to ensure uniqueness.",
                "why": "Original phrasing protects you from plagiarism flags and improves SEO rankings.",
                "input_hint": "Text that needs rephrasing",
                "output": "Uniquely rephrased version",
                "tool_slug": "paraphrasing-tool",
                "tool_name": "AI Paraphrasing Tool",
            },
            {
                "step": 4,
                "title": "Humanize AI-Written Text",
                "desc": "Make any AI-generated content sound natural and distinctly human.",
                "why": "AI-detection tools are widespread. Human-sounding text builds better audience trust.",
                "input_hint": "AI-generated text to humanize",
                "output": "Natural, human-sounding version",
                "tool_slug": "ai-humanizer",
                "tool_name": "AI Humanizer",
            },
            {
                "step": 5,
                "title": "Optimize for Search Engines",
                "desc": "Generate a meta description that makes search results click-worthy.",
                "why": "A good meta description can double your click-through rate from search.",
                "input_hint": "Page title and main topic",
                "output": "SEO-optimized meta description under 160 characters",
                "tool_slug": "meta-description-generator",
                "tool_name": "AI Meta Description Generator",
            },
        ],
    },
    {
        "slug": "grow-online-presence",
        "name": "Grow Online Presence",
        "tagline": "Build an audience that finds you",
        "icon": "bi-graph-up-arrow",
        "color_from": "#10B981",
        "color_to": "#3B82F6",
        "emoji": "📈",
        "problem": "You're creating content but nobody sees it. Your SEO is weak, your social posts don't get engagement, and you're shouting into the void.",
        "outcome": "A keyword-ranked content strategy, engaging social posts, and consistent visibility across channels.",
        "category_slug": "seo-tools",
        "steps": [
            {
                "step": 1,
                "title": "Group Your Keywords",
                "desc": "Cluster your target keywords into topical groups for a focused content strategy.",
                "why": "Topic clusters outrank isolated pages by 3× — this is how authority sites are built.",
                "input_hint": "Your seed keywords and niche",
                "output": "Keyword clusters organized by topic and intent",
                "tool_slug": "keyword-cluster-generator",
                "tool_name": "Keyword Cluster Generator",
            },
            {
                "step": 2,
                "title": "Write Your Cornerstone Article",
                "desc": "Generate a comprehensive, SEO-optimized article for your main keyword cluster.",
                "why": "One great cornerstone piece can drive compounding traffic for years.",
                "input_hint": "Main keyword, target audience, and subtopics to cover",
                "output": "Full SEO article with headings and keyword placement",
                "tool_slug": "seo-article-generator",
                "tool_name": "SEO Article Generator",
            },
            {
                "step": 3,
                "title": "Write a Blog Post",
                "desc": "Create supporting blog posts that link back to your cornerstone content.",
                "why": "Internal linking builds topical authority and distributes page rank.",
                "input_hint": "Blog topic and connection to your main article",
                "output": "Complete blog post ready to publish",
                "tool_slug": "blog-writer",
                "tool_name": "AI Blog Writer",
            },
            {
                "step": 4,
                "title": "Generate Instagram Captions",
                "desc": "Repurpose your content into Instagram captions that drive engagement.",
                "why": "Social proof amplifies SEO — engaged followers share content that earns backlinks.",
                "input_hint": "Your post topic or content to adapt",
                "output": "5 Instagram captions with hashtag suggestions",
                "tool_slug": "instagram-caption-generator",
                "tool_name": "Instagram Caption Generator",
            },
            {
                "step": 5,
                "title": "Write Your Meta Descriptions",
                "desc": "Craft click-worthy meta descriptions for each piece of published content.",
                "why": "Meta descriptions are your search ad copy — they determine if people click.",
                "input_hint": "Page title and main value proposition",
                "output": "Optimized meta description under 160 characters",
                "tool_slug": "meta-description-generator",
                "tool_name": "AI Meta Description Generator",
            },
        ],
    },
    {
        "slug": "build-and-ship",
        "name": "Build & Ship Software",
        "tagline": "Write better code, faster",
        "icon": "bi-terminal-fill",
        "color_from": "#06B6D4",
        "color_to": "#7B6FFF",
        "emoji": "⚡",
        "problem": "You're building but losing time on SQL, regex, debugging bugs, and reformatting code. Every detour costs you shipping time.",
        "outcome": "Clean queries, working patterns, debugged code, and shipped features — faster.",
        "category_slug": "developer-tools",
        "steps": [
            {
                "step": 1,
                "title": "Generate Your SQL Query",
                "desc": "Describe what data you need in plain English — get a working SQL query instantly.",
                "why": "Writing SQL from scratch is slow. AI-generated queries let you validate logic in seconds.",
                "input_hint": "What data you need and your table structure",
                "output": "Complete SQL query ready to run",
                "tool_slug": "sql-generator",
                "tool_name": "AI SQL Generator",
            },
            {
                "step": 2,
                "title": "Build a Regex Pattern",
                "desc": "Generate the exact regular expression you need from a plain English description.",
                "why": "Regex is powerful but cryptic. Spending 20 minutes on a pattern is never worth it.",
                "input_hint": "What the pattern should match or extract",
                "output": "Regex pattern with explanation and test cases",
                "tool_slug": "regex-generator",
                "tool_name": "AI Regex Generator",
            },
            {
                "step": 3,
                "title": "Debug Your Code",
                "desc": "Paste buggy code and a description of the problem — get the fix and an explanation.",
                "why": "Debugging is where most developer time disappears. AI speeds this up dramatically.",
                "input_hint": "Your code and description of the bug",
                "output": "Fixed code with explanation of what was wrong",
                "tool_slug": "code-debugger",
                "tool_name": "AI Code Debugger",
            },
            {
                "step": 4,
                "title": "Format Your JSON",
                "desc": "Clean and beautify messy JSON for readability and debugging.",
                "why": "Unformatted JSON is unreadable. Formatting is the difference between finding a bug in 10 seconds or 10 minutes.",
                "input_hint": "Raw or minified JSON",
                "output": "Beautifully formatted, validated JSON",
                "tool_slug": "json-formatter",
                "tool_name": "JSON Formatter",
            },
            {
                "step": 5,
                "title": "Write Your README",
                "desc": "Generate a professional README or documentation draft for your project.",
                "why": "Good documentation is what separates side projects from real products.",
                "input_hint": "Project name, description, and key features",
                "output": "Markdown README ready to ship",
                "tool_slug": "essay-writer",
                "tool_name": "AI Essay Writer",
            },
        ],
    },
    {
        "slug": "study-and-learn",
        "name": "Study & Learn Faster",
        "tagline": "Turn any subject into mastery",
        "icon": "bi-mortarboard-fill",
        "color_from": "#F59E0B",
        "color_to": "#10B981",
        "emoji": "🎓",
        "problem": "You have exams coming, tons to read, and can't figure out what matters. Notes are scattered, study time is wasted.",
        "outcome": "Organized notes, a focused study plan, a strong thesis, and quiz-ready understanding of your subject.",
        "category_slug": "student-tools",
        "steps": [
            {
                "step": 1,
                "title": "Summarize Your Notes",
                "desc": "Paste any lecture, article, or chapter — get clean, organized study notes.",
                "why": "Effective note structure is the foundation of retention. Raw text doesn't stick.",
                "input_hint": "Text from lecture, textbook, or article",
                "output": "Structured summary with key points and definitions",
                "tool_slug": "notes-generator",
                "tool_name": "AI Notes Generator",
            },
            {
                "step": 2,
                "title": "Generate Practice Questions",
                "desc": "Create quiz questions on any topic to test your understanding actively.",
                "why": "Active recall is 3× more effective than re-reading. Testing yourself is the fastest path to retention.",
                "input_hint": "Topic or notes text to quiz yourself on",
                "output": "Quiz questions with answer key",
                "tool_slug": "quiz-generator",
                "tool_name": "AI Quiz Generator",
            },
            {
                "step": 3,
                "title": "Craft a Strong Thesis Statement",
                "desc": "Generate a precise, arguable thesis for any essay or research paper.",
                "why": "A weak thesis makes the whole essay weak. Get it right at the start.",
                "input_hint": "Essay topic and your position or argument",
                "output": "3 thesis statement options ranked by strength",
                "tool_slug": "thesis-statement-generator",
                "tool_name": "Thesis Statement Generator",
            },
            {
                "step": 4,
                "title": "Write Your Essay",
                "desc": "Draft a full essay from your thesis statement, outline, and key arguments.",
                "why": "Once you have a thesis, a structured essay is just filling in the chapters.",
                "input_hint": "Essay topic, thesis, and main arguments",
                "output": "Complete essay ready for editing",
                "tool_slug": "essay-writer",
                "tool_name": "AI Essay Writer",
            },
            {
                "step": 5,
                "title": "Format Your Bibliography",
                "desc": "Generate a properly formatted bibliography from your sources.",
                "why": "Correct citations protect your academic integrity and save you from plagiarism penalties.",
                "input_hint": "List of your sources (author, title, year, URL)",
                "output": "Formatted bibliography in your required style",
                "tool_slug": "bibliography-generator",
                "tool_name": "Bibliography Generator",
            },
        ],
    },
]

# ── Lookup helpers ──────────────────────────────────────────────────────────

def get_journey(slug: str) -> dict | None:
    """Return a journey dict by slug, or None."""
    return next((j for j in JOURNEYS if j["slug"] == slug), None)


def get_journeys_for_tool(tool_slug: str) -> list[dict]:
    """Return all journeys that contain a given tool_slug as a step."""
    result = []
    for journey in JOURNEYS:
        for step in journey["steps"]:
            if step["tool_slug"] == tool_slug:
                result.append({
                    "journey": journey,
                    "step": step,
                    "step_number": step["step"],
                    "total_steps": len(journey["steps"]),
                    "prev_step": next(
                        (s for s in journey["steps"] if s["step"] == step["step"] - 1), None
                    ),
                    "next_step": next(
                        (s for s in journey["steps"] if s["step"] == step["step"] + 1), None
                    ),
                })
    return result
