# ---------------------------------------------------------------------------
# Extended LamGen ecosystem categories (merged into TOOL_CATEGORIES).
# Slugs here are the canonical DB slugs for the new verticals.
# ---------------------------------------------------------------------------

ECOSYSTEM_CATEGORY_SLUGS = frozenset({
    "education-ai",
    "seo-content",
    "social-viral",
    "finance-calculators",
    "health-medicine",
    "market-grocery",
    "electronics",
    "news-media",
    "sports-entertainment",
})

ECOSYSTEM_TOOL_CATEGORIES = [
    {
        "slug": "education-ai",
        "name": "Education & AI",
        "icon": "bi-mortarboard",
        "color_from": "#6366F1",
        "color_to": "#9333EA",
        "order": 90,
        "short_desc": "AI-assisted study, writing and research utilities.",
        "is_active": True,
        "tools": [
            {"slug": "ai-essay-outline-generator", "name": "AI Essay Outline Generator", "short_desc": "Generate a structured outline for your essay.", "icon": "bi-list-nested", "template_name": "tools/education/ai-essay-outline-generator.html", "tags": "ai,education,writing,essay,outline", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-thesis-statement-generator", "name": "AI Thesis Statement Generator", "short_desc": "Create a strong thesis statement for your paper.", "icon": "bi-journal-text", "template_name": "tools/education/ai-thesis-statement-generator.html", "tags": "ai,education,writing,thesis,statement", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-notes-summarizer", "name": "AI Notes Summarizer", "short_desc": "Summarize your notes into key points.", "icon": "bi-card-text", "template_name": "tools/education/ai-notes-summarizer.html", "tags": "ai,education,summary,notes", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-flashcard-generator", "name": "AI Flashcard Generator", "short_desc": "Create flashcards from your notes.", "icon": "bi-card-text", "template_name": "tools/education/ai-flashcard-generator.html", "tags": "ai,education,flashcards", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-study-planner", "name": "AI Study Planner", "short_desc": "Create a personalized study plan.", "icon": "bi-calendar-week", "template_name": "tools/education/ai-study-planner.html", "tags": "ai,education,study,plan", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-citation-generator", "name": "AI Citation Generator", "short_desc": "Generate citations in common academic formats.", "icon": "bi-quote", "template_name": "tools/education/ai-citation-generator.html", "tags": "ai,education,citation,generator", "order": 6, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "seo-content",
        "name": "SEO & Content",
        "icon": "bi-search",
        "color_from": "#059669",
        "color_to": "#16A34A",
        "order": 91,
        "short_desc": "AI-assisted SEO copy, titles and topical research.",
        "is_active": True,
        "tools": [
            {"slug": "ai-meta-description-generator", "name": "AI Meta Description Generator", "short_desc": "Generate SEO-friendly meta descriptions.", "icon": "bi-card-text", "template_name": "tools/seo/ai-meta-description-generator.html", "tags": "ai,seo,meta,description", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-blog-title-generator", "name": "AI Blog Title Generator", "short_desc": "Generate catchy blog titles.", "icon": "bi-type-h1", "template_name": "tools/seo/ai-blog-title-generator.html", "tags": "ai,seo,blog,title", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-keyword-intent-analyzer", "name": "AI Keyword Intent Analyzer", "short_desc": "Analyze the intent behind a keyword.", "icon": "bi-search", "template_name": "tools/seo/ai-keyword-intent-analyzer.html", "tags": "ai,seo,keyword,intent", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-faq-generator", "name": "AI FAQ Generator", "short_desc": "Generate FAQs for your content.", "icon": "bi-question-circle", "template_name": "tools/seo/ai-faq-generator.html", "tags": "ai,seo,faq,generator", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-youtube-title-generator", "name": "AI YouTube Title Generator", "short_desc": "Generate viral YouTube titles.", "icon": "bi-youtube", "template_name": "tools/seo/ai-youtube-title-generator.html", "tags": "ai,seo,youtube,title", "order": 5, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "social-viral",
        "name": "Social & Viral",
        "icon": "bi-share",
        "color_from": "#F97316",
        "color_to": "#EC4899",
        "order": 92,
        "short_desc": "Viral copy, captions and growth ideas for social platforms.",
        "is_active": True,
        "tools": [
            {"slug": "ai-caption-generator", "name": "AI Caption Generator", "short_desc": "Generate scroll-stopping captions for any platform.", "icon": "bi-chat-square-text", "template_name": "tools/social_viral/ai-caption-generator.html", "tags": "ai,social,caption,instagram,tiktok", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-viral-hook-generator", "name": "AI Viral Hook Generator", "short_desc": "Generate opening hooks for short-form video scripts.", "icon": "bi-lightning-charge", "template_name": "tools/social_viral/ai-viral-hook-generator.html", "tags": "ai,social,hook,viral,video", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-carousel-copy-generator", "name": "AI Carousel Copy Generator", "short_desc": "Outline multi-slide carousel posts with CTA lines.", "icon": "bi-collection", "template_name": "tools/social_viral/ai-carousel-copy-generator.html", "tags": "ai,social,carousel,linkedin,instagram", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "ai-reels-script-outline", "name": "AI Reels Script Outline", "short_desc": "Turn a topic into a tight reels / shorts script beat sheet.", "icon": "bi-camera-video", "template_name": "tools/social_viral/ai-reels-script-outline.html", "tags": "ai,social,reels,shorts,script", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "social-content-calendar-planner", "name": "Social Content Calendar Planner", "short_desc": "Plan a week of themed posts across channels.", "icon": "bi-calendar3", "template_name": "tools/social_viral/social-content-calendar-planner.html", "tags": "social,calendar,planner,content", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "engagement-benchmark-estimator", "name": "Engagement Benchmark Estimator", "short_desc": "Estimate expected engagement ranges from reach and niche.", "icon": "bi-graph-up-arrow", "template_name": "tools/social_viral/engagement-benchmark-estimator.html", "tags": "social,engagement,benchmark,analytics", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "platform-tone-rewriter", "name": "Platform Tone Rewriter", "short_desc": "Rewrite the same idea for Twitter, LinkedIn and TikTok tones.", "icon": "bi-arrow-left-right", "template_name": "tools/social_viral/platform-tone-rewriter.html", "tags": "social,tone,rewrite,copy", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "influencer-collab-pitch-generator", "name": "Influencer Collab Pitch Generator", "short_desc": "Draft outreach pitches for brand or creator collabs.", "icon": "bi-envelope-paper-heart", "template_name": "tools/social_viral/influencer-collab-pitch-generator.html", "tags": "social,influencer,pitch,outreach", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "finance-calculators",
        "name": "Finance & Calculators",
        "icon": "bi-calculator",
        "color_from": "#CA8A04",
        "color_to": "#D97706",
        "order": 93,
        "short_desc": "Regional tax, salary and day-to-day finance calculators.",
        "is_active": True,
        "tools": [
            {"slug": "bangladesh-tax-calculator", "name": "Bangladesh Tax Calculator", "short_desc": "Estimate income tax under common Bangladesh slabs (indicative).", "icon": "bi-bank", "template_name": "tools/finance_calculators/bangladesh-tax-calculator.html", "tags": "tax,bangladesh,salary,finance", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "salary-pay-slip-estimator-bd", "name": "Salary Pay Slip Estimator (BD)", "short_desc": "Estimate net pay from gross with common allowances.", "icon": "bi-cash-stack", "template_name": "tools/finance_calculators/salary-pay-slip-estimator-bd.html", "tags": "salary,pay,bangladesh,net,gross", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "vat-inclusive-price-calculator-bd", "name": "VAT Inclusive Price Calculator (BD)", "short_desc": "Add or strip VAT from prices with configurable rates.", "icon": "bi-receipt", "template_name": "tools/finance_calculators/vat-inclusive-price-calculator-bd.html", "tags": "vat,bangladesh,price,tax", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "gratuity-calculator-bd", "name": "Gratuity Calculator (BD)", "short_desc": "Estimate gratuity from tenure and last drawn salary.", "icon": "bi-piggy-bank", "template_name": "tools/finance_calculators/gratuity-calculator-bd.html", "tags": "gratuity,bangladesh,salary,employment", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "remittance-fee-comparator", "name": "Remittance Fee Comparator", "short_desc": "Compare total landed cost across fee and FX spread scenarios.", "icon": "bi-send", "template_name": "tools/finance_calculators/remittance-fee-comparator.html", "tags": "remittance,fees,fx,finance", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "fixed-deposit-maturity-calculator", "name": "Fixed Deposit Maturity Calculator", "short_desc": "Project maturity value with compound frequency and TDS hints.", "icon": "bi-graph-up", "template_name": "tools/finance_calculators/fixed-deposit-maturity-calculator.html", "tags": "fd,deposit,interest,maturity", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "house-rent-allowance-calculator-bd", "name": "House Rent Allowance Optimizer (BD)", "short_desc": "Explore HRA scenarios against basic salary splits.", "icon": "bi-house", "template_name": "tools/finance_calculators/house-rent-allowance-calculator-bd.html", "tags": "hra,rent,bangladesh,salary", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "loan-emi-comparison-table", "name": "Loan EMI Comparison Table", "short_desc": "Compare two loan offers side by side with EMI and total interest.", "icon": "bi-table", "template_name": "tools/finance_calculators/loan-emi-comparison-table.html", "tags": "loan,emi,compare,interest", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "health-medicine",
        "name": "Health & Medicine",
        "icon": "bi-heart-pulse",
        "color_from": "#DC2626",
        "color_to": "#DB2777",
        "order": 94,
        "short_desc": "Educational health utilities — not a substitute for professional care.",
        "is_active": True,
        "tools": [
            {"slug": "medicine-information-finder", "name": "Medicine Information Finder", "short_desc": "Look up high-level medicine info and interaction prompts (educational).", "icon": "bi-capsule", "template_name": "tools/health_medicine/medicine-information-finder.html", "tags": "medicine,health,drug,information", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "otc-dosage-reference-guide", "name": "OTC Dosage Reference Guide", "short_desc": "Reference-style OTC dosing reminders with strong disclaimers.", "icon": "bi-journal-medical", "template_name": "tools/health_medicine/otc-dosage-reference-guide.html", "tags": "otc,dosage,health,reference", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "generic-vs-brand-explainer", "name": "Generic vs Brand Explainer", "short_desc": "Explain common differences between generic and brand medicines.", "icon": "bi-shuffle", "template_name": "tools/health_medicine/generic-vs-brand-explainer.html", "tags": "generic,brand,pharmacy,education", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "hydration-needs-estimator", "name": "Hydration Needs Estimator", "short_desc": "Estimate daily fluid targets from weight and activity.", "icon": "bi-droplet-half", "template_name": "tools/health_medicine/hydration-needs-estimator.html", "tags": "hydration,water,health,fitness", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "medical-term-decoder", "name": "Medical Term Decoder", "short_desc": "Break down common medical jargon into plain language.", "icon": "bi-book", "template_name": "tools/health_medicine/medical-term-decoder.html", "tags": "medical,terms,plain,language", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "prescription-label-checklist", "name": "Prescription Label Checklist", "short_desc": "Checklist to verify you understood prescription label fields.", "icon": "bi-check2-square", "template_name": "tools/health_medicine/prescription-label-checklist.html", "tags": "prescription,label,safety,checklist", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "vaccination-schedule-planner", "name": "Vaccination Schedule Planner", "short_desc": "Plan reminder dates from a vaccine series interval table.", "icon": "bi-calendar-check", "template_name": "tools/health_medicine/vaccination-schedule-planner.html", "tags": "vaccine,schedule,planner,health", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "symptom-journal-template-builder", "name": "Symptom Journal Template Builder", "short_desc": "Generate a printable symptom journal template for clinician visits.", "icon": "bi-clipboard-data", "template_name": "tools/health_medicine/symptom-journal-template-builder.html", "tags": "symptom,journal,template,health", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "market-grocery",
        "name": "Market & Grocery",
        "icon": "bi-cart3",
        "color_from": "#EA580C",
        "color_to": "#CA8A04",
        "order": 95,
        "short_desc": "Grocery budgeting, lists and market comparison helpers.",
        "is_active": True,
        "tools": [
            {"slug": "grocery-budget-estimator", "name": "Grocery Budget Estimator", "short_desc": "Estimate monthly grocery spend from household size and diet style.", "icon": "bi-wallet2", "template_name": "tools/market_grocery/grocery-budget-estimator.html", "tags": "grocery,budget,household,food", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "unit-price-comparison-calculator", "name": "Unit Price Comparison Calculator", "short_desc": "Compare two SKUs using price per unit.", "icon": "bi-calculator", "template_name": "tools/market_grocery/unit-price-comparison-calculator.html", "tags": "unit,price,compare,grocery", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "meal-prep-cost-splitter", "name": "Meal Prep Cost Splitter", "short_desc": "Split bulk ingredient cost across meals and portions.", "icon": "bi-egg-fried", "template_name": "tools/market_grocery/meal-prep-cost-splitter.html", "tags": "meal,prep,cost,grocery", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "bangladesh-grocery-price-sheet", "name": "Bangladesh Grocery Price Sheet", "short_desc": "Editable reference table for tracking local staple prices.", "icon": "bi-table", "template_name": "tools/market_grocery/bangladesh-grocery-price-sheet.html", "tags": "bangladesh,grocery,prices,market", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "shopping-list-optimizer", "name": "Shopping List Optimizer", "short_desc": "Group a shopping list by store aisle templates.", "icon": "bi-list-check", "template_name": "tools/market_grocery/shopping-list-optimizer.html", "tags": "shopping,list,store,grocery", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "recipe-cost-calculator", "name": "Recipe Cost Calculator", "short_desc": "Compute dish cost from ingredient lines with quantities.", "icon": "bi-cash-coin", "template_name": "tools/market_grocery/recipe-cost-calculator.html", "tags": "recipe,cost,cooking,grocery", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "pantry-shelf-life-tracker", "name": "Pantry Shelf Life Tracker", "short_desc": "Track opened packages and suggested use-by reminders.", "icon": "bi-hourglass-split", "template_name": "tools/market_grocery/pantry-shelf-life-tracker.html", "tags": "pantry,shelf,life,grocery", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "bulk-buy-vs-retail-calculator", "name": "Bulk Buy vs Retail Calculator", "short_desc": "Decide if bulk pricing beats retail after spoilage risk.", "icon": "bi-box-seam", "template_name": "tools/market_grocery/bulk-buy-vs-retail-calculator.html", "tags": "bulk,retail,compare,grocery", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "electronics",
        "name": "Electronics",
        "icon": "bi-phone",
        "color_from": "#0891B2",
        "color_to": "#2563EB",
        "order": 96,
        "short_desc": "Compare devices, specs and ownership costs.",
        "is_active": True,
        "tools": [
            {"slug": "electronics-price-comparison", "name": "Electronics Price Comparison", "short_desc": "Compare two or three listings with fees, warranty and extras.", "icon": "bi-currency-exchange", "template_name": "tools/electronics/electronics-price-comparison.html", "tags": "electronics,price,compare,shopping", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "smartphone-spec-comparison", "name": "Smartphone Spec Comparison", "short_desc": "Side-by-side spec diff for phones you are choosing between.", "icon": "bi-phone", "template_name": "tools/electronics/smartphone-spec-comparison.html", "tags": "phone,specs,compare,electronics", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "laptop-filter-by-specs", "name": "Laptop Filter by Specs", "short_desc": "Score laptops against your minimum CPU, RAM and display needs.", "icon": "bi-laptop", "template_name": "tools/electronics/laptop-filter-by-specs.html", "tags": "laptop,specs,filter,electronics", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "monitor-resolution-ppi-calculator", "name": "Monitor Resolution PPI Calculator", "short_desc": "Calculate PPI and rough readability for monitor sizes.", "icon": "bi-display", "template_name": "tools/electronics/monitor-resolution-ppi-calculator.html", "tags": "monitor,ppi,resolution,display", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "power-bank-capacity-estimator", "name": "Power Bank Capacity Estimator", "short_desc": "Estimate effective phone charges from rated mAh and efficiency.", "icon": "bi-battery-charging", "template_name": "tools/electronics/power-bank-capacity-estimator.html", "tags": "power,bank,mah,charger", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "warranty-end-date-calculator", "name": "Warranty End Date Calculator", "short_desc": "Compute warranty end from purchase date and duration.", "icon": "bi-shield-check", "template_name": "tools/electronics/warranty-end-date-calculator.html", "tags": "warranty,date,electronics", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "energy-usage-cost-calculator", "name": "Energy Usage Cost Calculator", "short_desc": "Estimate electricity cost from device wattage and hours.", "icon": "bi-lightning-charge", "template_name": "tools/electronics/energy-usage-cost-calculator.html", "tags": "energy,watt,kwh,cost", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "cable-connector-id-guide", "name": "Cable & Connector ID Guide", "short_desc": "Match common cable ends to names and typical use cases.", "icon": "bi-usb-symbol", "template_name": "tools/electronics/cable-connector-id-guide.html", "tags": "cable,connector,usb,hdmi", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "news-media",
        "name": "News & Media",
        "icon": "bi-newspaper",
        "color_from": "#475569",
        "color_to": "#0F172A",
        "order": 97,
        "short_desc": "Directories and planning tools for news, TV and publishing.",
        "is_active": True,
        "tools": [
            {"slug": "live-tv-directory", "name": "Live TV Directory", "short_desc": "Curated links hub for major live TV schedules and streams (region aware).", "icon": "bi-tv", "template_name": "tools/news_media/live-tv-directory.html", "tags": "tv,live,directory,media", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "bangla-newspaper-directory", "name": "Bangla Newspaper Directory", "short_desc": "Quick access directory of leading Bangla news sites.", "icon": "bi-globe2", "template_name": "tools/news_media/bangla-newspaper-directory.html", "tags": "bangla,newspaper,directory,news", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "rss-feed-merge-preview", "name": "RSS Feed Merge Preview", "short_desc": "Preview merged headlines from multiple RSS feeds.", "icon": "bi-rss", "template_name": "tools/news_media/rss-feed-merge-preview.html", "tags": "rss,feeds,news,reader", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "news-source-bias-checklist", "name": "News Source Bias Checklist", "short_desc": "Structured checklist to compare framing across outlets.", "icon": "bi-check2-all", "template_name": "tools/news_media/news-source-bias-checklist.html", "tags": "news,bias,media,literacy", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "press-release-headline-grader", "name": "Press Release Headline Grader", "short_desc": "Score headline length, clarity and keyword presence.", "icon": "bi-type", "template_name": "tools/news_media/press-release-headline-grader.html", "tags": "press,release,headline,pr", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "newsletter-outline-generator", "name": "Newsletter Outline Generator", "short_desc": "Generate section outlines for weekly email newsletters.", "icon": "bi-envelope-open", "template_name": "tools/news_media/newsletter-outline-generator.html", "tags": "newsletter,outline,email,media", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "podcast-topic-researcher", "name": "Podcast Topic Researcher", "short_desc": "Brainstorm episode angles from a seed topic and audience.", "icon": "bi-mic", "template_name": "tools/news_media/podcast-topic-researcher.html", "tags": "podcast,topic,research,media", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "fact-check-prompt-builder", "name": "Fact-Check Prompt Builder", "short_desc": "Build structured prompts to verify claims with sources.", "icon": "bi-patch-check", "template_name": "tools/news_media/fact-check-prompt-builder.html", "tags": "fact,check,prompt,news", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
    {
        "slug": "sports-entertainment",
        "name": "Sports & Entertainment",
        "icon": "bi-trophy",
        "color_from": "#65A30D",
        "color_to": "#15803D",
        "order": 98,
        "short_desc": "Scores, fantasy helpers and watch-party utilities.",
        "is_active": True,
        "tools": [
            {"slug": "live-sports-score-tracker", "name": "Live Sports Score Tracker", "short_desc": "Track live scores and fixtures via embedded links and manual refresh.", "icon": "bi-broadcast", "template_name": "tools/sports_entertainment/live-sports-score-tracker.html", "tags": "sports,scores,live,tracker", "order": 1, "is_active": True, "is_ai_powered": False},
            {"slug": "fantasy-points-estimator", "name": "Fantasy Points Estimator", "short_desc": "Rough projected fantasy points from stat line assumptions.", "icon": "bi-graph-up", "template_name": "tools/sports_entertainment/fantasy-points-estimator.html", "tags": "fantasy,sports,points,estimate", "order": 2, "is_active": True, "is_ai_powered": False},
            {"slug": "tournament-bracket-builder", "name": "Tournament Bracket Builder", "short_desc": "Build single-elimination brackets for local tournaments.", "icon": "bi-diagram-3", "template_name": "tools/sports_entertainment/tournament-bracket-builder.html", "tags": "bracket,tournament,sports", "order": 3, "is_active": True, "is_ai_powered": False},
            {"slug": "sports-stat-comparison", "name": "Sports Stat Comparison", "short_desc": "Compare two athletes across a small set of manual stat inputs.", "icon": "bi-bar-chart-line", "template_name": "tools/sports_entertainment/sports-stat-comparison.html", "tags": "sports,stats,compare,analytics", "order": 4, "is_active": True, "is_ai_powered": False},
            {"slug": "watch-party-checklist", "name": "Watch Party Checklist", "short_desc": "Checklist for hosting streaming sports watch parties.", "icon": "bi-people", "template_name": "tools/sports_entertainment/watch-party-checklist.html", "tags": "watch,party,entertainment,sports", "order": 5, "is_active": True, "is_ai_powered": False},
            {"slug": "player-prop-line-explainer", "name": "Player Prop Line Explainer", "short_desc": "Explain common player prop bet formats in plain language.", "icon": "bi-question-circle", "template_name": "tools/sports_entertainment/player-prop-line-explainer.html", "tags": "props,betting,education,sports", "order": 6, "is_active": True, "is_ai_powered": False},
            {"slug": "stadium-seat-view-estimator", "name": "Stadium Seat View Estimator", "short_desc": "Rough sightline notes from section, row and sport venue type.", "icon": "bi-geo-alt", "template_name": "tools/sports_entertainment/stadium-seat-view-estimator.html", "tags": "stadium,seat,view,sports", "order": 7, "is_active": True, "is_ai_powered": False},
            {"slug": "halftime-show-bingo-card", "name": "Halftime Show Bingo Card", "short_desc": "Generate a novelty bingo card for big-game halftime moments.", "icon": "bi-grid-3x3-gap", "template_name": "tools/sports_entertainment/halftime-show-bingo-card.html", "tags": "bingo,halftime,entertainment", "order": 8, "is_active": True, "is_ai_powered": False},
        ],
    },
]
