# Generated by Django 4.2.16 on 2026-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='default', max_length=50)),
                ('prompt_type', models.CharField(default='text', max_length=50)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
