# Generated by Django 4.2.16 on 2026-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_toolusagehistory_unique_constraint'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocategory',
            name='schema_type',
            field=models.CharField(choices=[('ItemList', 'ItemList'), ('FAQPage', 'FAQPage'), ('Article', 'Article')], default='ItemList', max_length=30),
        ),
        migrations.AddField(
            model_name='seopage',
            name='related_tools',
            field=models.ManyToManyField(blank=True, related_name='seo_pages', to='tools.tool'),
        ),
    ]
