# Generated by Django 4.2.16 on 2026-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolusagehistory',
            name='used_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
