# Generated by Django 4.2.16 on 2026-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_toolusagehistory_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text='List of {"q": question, "a": answer} dicts'),
        ),
        migrations.AddField(
            model_name='tool',
            name='seo_intro',
            field=models.TextField(blank=True, help_text='Unique 200-300 word intro for tool page'),
        ),
        migrations.AddField(
            model_name='tool',
            name='use_cases',
            field=models.JSONField(blank=True, default=list, help_text='List of use case descriptions'),
        ),
    ]
